# Generated by Django 5.1.4 on 2025-03-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
