# Generated by Django 5.1.4 on 2025-03-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('DS', 'Design'), ('CL', 'Culture'), ('SC', 'Science')], default='TL', max_length=2),
        ),
    ]
