# Generated by Django 5.1.4 on 2025-03-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=10),
        ),
    ]
