# Generated by Django 5.1.4 on 2025-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='img',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
